### ISSUE TITLE
fuse3

### ISSUE THREAD

**Issue by jgrover** [fkie-cad/pcapFS#14]
During an Ubuntu 18.04 install, the install-all-dependencies.sh script fails when looking for /etc/init.d/fuse3.  The file does not exist.  Anyone find a way to make this work?

**Comment by jgrover** [comment]
The exact message is:
`Running custom install script '/home/vagrant/pcapfs/3rdparty/libfuse/util/install_helper.sh /home/vagrant/pcapfs/scripts/dependencies/../../dependencies/etc /home/vagrant/pcapfs/scripts/dependencies/../../dependencies/bin /lib/udev/rules.d' update-rc.d: error: unable to read /etc/init.d/fuse3`

The update-all-dependencies script actually finishes and says it installed successfully, but when running "make" later on we get fuse errors.

**Comment by dl8bh** [comment]
Hi @jgrover, have a look at
https://github.com/fkie-cad/pcapFS/issues/13 which is the same bug.
Until this issue is fixed, you have to change libfuse in 3rdparty/libfuse to a working tag (f.e. fuse-3.4.1) and to build libfuse again.
After this,  you can build pcapfs again-

**Comment by 0x4d4c** [comment]
@jgrover, we pushed a new version to the master branch solving https://github.com/fkie-cad/pcapFS/issues/13. Could you please check whether this also solves your problem?

**Comment by jgrover** [comment]
Yes, this fixed the problem.  Thank you!
