### ISSUE TITLE
building pcapFS fails  - make with error

### ISSUE THREAD

**Issue by code-dummy** [fkie-cad/pcapFS#15]
Hi all,
I have tried to build pcapFS; cmake works great but the make interrupts with error:
error: invalid conversion from ‘const uint8_t*’ {aka ‘const unsigned char*’} to ‘uint8_t*’
and so on ...
Please see attached file make.error.txt.
Could some help me please.
I did all the described steps to build.
My OS:
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
Linux Analyzer 5.3.0-23-generic #25-Ubuntu SMP Tue Nov 12 09:22:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[make.error.txt](https://github.com/fkie-cad/pcapFS/files/3916064/make.error.txt)

In advance thank you very much.
Jo

**Comment by fxb-cocacoding** [comment]
Hi Jo,

thanks for your report.
Apparently we are mixing constant and non-constant variables.
Are you using GCC 9.1.0? I think we haven't tested anything higher than 8.3.0 yet.
We will work on a fix.

Best regards,
fxb

**Comment by 0x4d4c** [comment]
Hi Jo,
we have a fix ready. After some final tests, we'll update the master branch.

And thanks for reporting!

**Comment by 0x4d4c** [comment]
master and dev are updated. @code-dummy could you please test if everything works for you now? If not, feel free to reopen this issue.

**Comment by code-dummy** [comment]
Hallo Martin,

gute Arbeit ;-)
Das make läuft jetzt so durch, habe ein pcapfs bauen können und funktioniert.
Vielen Dank für die schnelle Reaktion und auch Lösung.

LG
Josh
