### ISSUE TITLE
Support for spaces in file names

### ISSUE THREAD

**Issue by 0x4d4c** [fkie-cad/pcapFS#20]
Trying to mount a pcap with spaces in its name gives the following error: `the argument ('test capture.pcap') for option '--pcap-path' is invalid`. This happens when the name is quoted on the command line and when the space is escaped. Directories with a space in their name cause the same error.

I think is a bug and pcapFS should support input file names with spaces.

**Comment by axmahr** [comment]
Thanks for catching this bug! The issue included all command line arguments containing escaped space characters. It should be fixed now.
